name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: registry.digitalocean.com/lukaskubec
  IMAGE_NAME: meme-page-selfhosted

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "Selfhosted"
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_AT }}

      - run: doctl registry login --expiry-seconds 600

      - name: Push image
        run: docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: "Selfhosted"
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PK }}
          passphrase: ${{ secrets.PP }}
          envs: REGISTRY=$REGISTRY IMAGE_NAME=$IMAGE_NAME
          script: |
            # Login to registry
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            # Stop running container 
            docker stop $(echo $IMAGE_NAME)
            # Remove old container
            docker rm $(echo $IMAGE_NAME)
            # Run a new container from a new image
            docker run -d \
            -p 80:3000 \
            --restart always \
            --name $(echo $IMAGE_NAME) \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
