name: Build and Deploy to DO app platform

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REPOSITORY: lukaskubec
  IMAGE_NAME: memes

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.sha.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: pre_job
    environment: "DO_APP"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_AT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ needs.pre_job.outputs.sha_short }}
            ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: ["build", "pre_job"]
    environment: "DO_APP"
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_AT_DEPLOY }}
      - name: Deploy to DO app platform
        run: doctl apps create-deployment ${{ secrets.DO_APP_ID }} --force-rebuild
