name: Build and Deploy to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REPOSITORY: lukaskubec
  IMAGE_NAME: memes

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "AZURE"
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t $REPOSITORY/$IMAGE_NAME:${{ github.sha }} .
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_AT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            $REPOSITORY/$IMAGE_NAME:${{ github.sha }}
            $REPOSITORY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: "AZURE"
    steps:
        - name: Log in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.CRED }}
        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            imageToDeploy: $REPOSITORY/$IMAGE_NAME:${{ github.sha }}
            registryUrl: registry-1.docker.io
            registryUsername: ${{ secrets.DOCKERHUB_USER }}
            registryPassword: ${{ secrets.DOCKERHUB_AT }}
            containerAppName: ${{ secrets.AZ_APP }}
            resourceGroup: ${{ secrets.AZ_RG }}
