name: Build and Deploy to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REPOSITORY: lukaskubec
  IMAGE_NAME: memes

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "DO_APP"
    steps:
      - uses: actions/checkout@v4
      - name: Get short SHA
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_AT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.SHA_SHORT }}
            ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: "DO_APP"
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: my_DO_app
          token: ${{ secrets.DO_AT }}
          images: '[
                    {
                      "name": "seal-app",
                      "image":{
                        "registry_type": "DOCKER_HUB",
                        "registry": "${{ env.REPOSITORY }}",
                        "repository": "${{ env.IMAGE_NAME }}",
                        "tag": "${{ env.SHA_SHORT }}"
                      },
                  ]'
