name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: registry.digitalocean.com/lukaskubec
  IMAGE_NAME: meme-page-selfhosted

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "Selfhosted"
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_AT }}

      - run: doctl registry login --expiry-seconds 600

      - name: Push image
        run: docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: "Selfhosted"
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PK }}
          passphrase: ${{ secrets.PP }}
          envs: REGISTRY,IMAGE_NAME
          script: |
            # Stop and remove containers only if they exist
            RUNNING_CONTAINERS=$(docker ps -q)
            if [ ! -z "$RUNNING_CONTAINERS" ]; then
              docker stop $RUNNING_CONTAINERS
            fi
            STOPPED_CONTAINERS=$(docker ps -a -q)
            if [ ! -z "$STOPPED_CONTAINERS" ]; then
              docker rm $STOPPED_CONTAINERS
            fi
            # Run a new container from a new image
            # Login to registry
            echo ${{ secrets.DO_AT }} | docker login -u ${{ secrets.DO_USER }} --password-stdin registry.digitalocean.com
            docker pull $REGISTRY/$IMAGE_NAME:latest
            docker run -d \
            -p 80:3000 \
            --restart always \
            --name $IMAGE_NAME \
            $REGISTRY/$IMAGE_NAME:latest
